# APP
app:
  access-limit: 1000000

# GRPC
grpc:
  port: 9090

# KAFKA
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      output:
        destination: access-topic
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    properties:
      retry.backoff.ms: 1000
    security:
      protocol: PLAINTEXT

# REDIS
redisson:
  config: |
    singleServerConfig:
      address: "redis://localhost:6379"
      connectionMinimumIdleSize: 2
      connectionPoolSize: 10
    threads: 4
    nettyThreads: 4
