# General
app:
  kafka:
    topic: access-topic

# KAFKA
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: access-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
